config/routes.rb
Bprds::Application.routes.draw do

  match 'education' => 'home#education', :as => :education
  match 'health' => 'home#health', :as => :health
  match 'contact_us' => 'home#contact', :as => :contact

  root :to => "home#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def education

  end

  def health

  end

  def contact

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<div id="site_content">
  <div id="content">
    <ul>
      <li>Name of the organization	:  BAHARPOTA  PREMTIRTHA  RURAL  DEVELOPMENT  SOCIETY</li>
      <li>Postal  Address		: Vill &Po – Baharpota, Block-Panskura-1, P.S,-Panskura,Dist-Purba Medinipur
					   Pin-721151, West Bengal, India.</li>
      <li>E-MAIL			:  bprds96@rediffmail.com, bprds@rediffmail.com</li>
      <li>Phone Number		:  91-03228251955-91-03228251026. M(9733547451)</li>
      <li>Name & Designation of Chief:  Krishnendu  Chakrabarty(Secretary).</li>
     </ul>
  </div>
  <div id="site_content_bottom"></div>
</div>

app/views/home/education.html.erb
<div id="site_content">
  <div id="panel_health" class="carousel slide">
    <div class="carousel-inner">
      <div class="item active"><img src="images/education_2.jpg" alt="bprds" /></div>
      <div class="item"><img src="images/education_2.jpg" alt="bprds" /></div>
      <div class="item"><img src="images/education_1.jpg" alt="bprds" /></div>
    </div>
     <a class="carousel-control left" href="#panel_health" data-slide="prev">&lsaquo;</a>
     <a class="carousel-control right" href="#panel_health" data-slide="next">&rsaquo;</a>
  </div>
  <div id="content">
    <p>Education which is a crying need of our society has not been spread among all. The over all literacy is only 43% and the female literacy is just 22%. Not even 50% of the children are enrolled in formal school. All around 50% of those who has completed standard four enroll for upper primary education but there are only few who go for higher secondary education.</p>
  <p>We are social animal and we have some social duties. So our education centre has taken an important role in spreading education. We help poor and lower middle-class students in different ways so that they can continue their studies. We live in a remote village which is far a way from town. So the students do not get any farther educational details. Our centre helps them with modern education system. We help them with study materials from primary to higher secondary. We also provide them coaching which is mainly free of cost for the poor and economically backward families. This coaching is organized by the good educated persons who are not employed any where. For this many children are coming to our education centre.</p>
  <p> To continue this education centre some financial help is also needed. If we get help from any agencies we shall be able to continue our education centre in future. We believe that our education centre will help to reduce illiteracy from our society.</p>
  </div>
  <div id="site_content_bottom"></div>
</div>

app/views/home/health.html.erb
<div id="site_content">
  <div id="panel_health" class="carousel slide">
    <div class="carousel-inner">
      <div class="item active"><img src="images/health_4.jpg" alt="bprds" /></div>
      <div class="item"><img src="images/health_3.jpg" alt="bprds" /></div>
      <div class="item"><img src="images/health_2.jpg" alt="bprds" /></div>
      <div class="item"><img src="images/health_1.jpg" alt="bprds" /></div>
    </div>
     <a class="carousel-control left" href="#panel_health" data-slide="prev">&lsaquo;</a>
     <a class="carousel-control right" href="#panel_health" data-slide="next">&rsaquo;</a>
  </div>
  <div id="content">
    <p>Our Society has taken a prominent role to fight against all the deadly diseases. The inhabitants of our locality have no other source of income without cultivation. The small income cannot able to give proper food, education and treatment to the children and family. So, some people have to go to different states to earn money and they bring with them deadly diseases like HIV / AIDS / TB etc. Under these circumstances, our organization can  not remain inactive closing their hands.</p>
  <p>We have primary health centers with eminent doctors and with medicines. Our doctors are treating the patients carefully. Not only that from our dispensary the medicine and treatment are supplied to Patients free of cost. The charitable dispensary is open 6 days in week. Our specialist doctors have taken full responsibility to treat the patients.  Even Eye treatment camp is held once in a month by the efforts of our organization. Besides treatment, we arrange Health awareness programmes once in a month to make aware patients and common people about various diseases.</p>
  <p>We also have arranged an yogic and massage centre. This helps the youngers to build their body healthy. The olders who are suffering from various diseases get relief here. Hearing this many other people are coming to our centre.</p>
  <p>This organization with the limited resources has been trying hard since inception to remove the impress from the social development works. The results are so far good with every good yield economic activities and generation of social awareness and consciousness among the people.</p>
  <p>We are stepping, for warding and holding with so many prospectus and projects for the welfare and social improvements of local, distressed, disabled, Aged and poor SC / ST / OBC people. We are running programmes on TB, HIV, and AIDS in the rural and conservative areas to make them aware of these deadly diseases and agree to come under the light of treatment. We are the organization itself bears the expenditure for the said programme. Also, many distinguished persons and medical representatives in our locality have donated the medicine for this programme. By this programme the rural backward SC / ST / OBC Minorities / Poor people in our locality are being benefited. The society during the year conduct distribution of medicine, proper helping and so many medical camps are held with the co-operation of local people.</p>
  </div>
  <div id="site_content_bottom"></div>
</div>

app/views/home/index.html.erb
<div id="site_content">
  <div id="panel_health"><img src="images/home.png" alt="bprds" /></div>
  <div id="content">
  <!-- insert the page content here -->
    <p>BAHARPOTA PREMTIRTHA RURAL DEVELOPMENT SOCIETY in its mission for divine endeavor for the people has always followed the above proverb on acute footing. In it’s bottom up approach it has maintained than a vertical line of management, which can be reflected as underneath.</p>
  <p>Around 50% of those who complete standard four enroll for upper primary education and there are only few who go for higher secondary education. Early childhood education or pre-primary education of these people has been improved. Recent thrust on total literacy programmed in Purba Medinipur district has improved recently quite satisfactory. But in post literacy programmed (Which should have component of awareness and functional literacy) was not ensured properly. They will retain there past start of illiterates.</p>

  <h1>OUR MISSION</h1>
  <ul>
    <li>Enhanced Peoples participation in the development process.</li>
    <li>Intact peoples awareness through I.E. (In-formation Education and communication)</li>
    <li>Organize women around their issues of immance.</li>
    <li>Actyalize peoples movement for development.</li>
    <li>Take all appropriate need based programmes of the people, by the people and for the people.</li>
  </ul>

  <h1>OUR VISSION</h1>
  <ul>
    <li>Socio-economic Development.</li>
    <li>Promote small scale Industries.</li>
    <li>Communicating media between Government and Mass.</li>
    <li>Interacting with the various implementing agencies.</li>
    <li>Human Resource Development.<li>
    <li>Health, Education and Culture.</li>
  </ul>
  <h1>OUR AIMS</h1>
  <ul>
    <li>To activate the developmental activities among the people of this vicinity.</li>
    <li>To develop the surrounding areas both economically and psychologically.</li>
    <li>To entact formation of socialistic pattern of society.</li>
    <li>To participate information of network of NGO’s.</li>
    <li>To train & help the people.</li>
    <li>To eradicate illiteracy, untouchability etc.</li>
    <li>To grow conception of awareness, participation in activities among the people.</li>
  </ul>
  <h1>OUR TARGET</h1>
  <ul>
    <li>People below the proverty line.</li>
    <li>People of the downtrodden Sector.</li>
    <li>Women form the weaker sector.</li>
    <li>Destitute.</li>
    <li>Orphans.</li>
    <li>People of the Aged etc.</li>
  </ul>
  </div>
  <div id="site_content_bottom"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
  <title>BAHARPOTA PREMTIRTHA RURAL DEVLOPMENT SOCIETY</title>
  <%= javascript_include_tag "jquery","bootstrap", "bootstrap-carousel","application" %>
  <%= stylesheet_link_tag "style","bootstrap" %>
<body>
  <div id="main">
    <div id="links"></div>
    <div id="header">
      <div id="logo">
        <div id="logo_text">
          <h1>Baharpota <span class="alternate_colour">Premtirtha </span>Rural <span class="alternate_colour">Devlopment </span>Society</h1>
        </div>
      </div>
      <div id="menubar">
        <ul id="menu">
          <!-- put class="tab_selected" in the li tag for the selected page - to highlight which page you're on -->
          <li class="<%= params[:action] == 'index' ? 'tab_selected' : ''%>"><%= link_to "Home", root_path%></li>
          <li class="<%= params[:action] == 'education' ? 'tab_selected' : ''%>"><%= link_to "Education", education_path%></li>
          <li class="<%= params[:action] == 'health' ? 'tab_selected' : ''%>"><%= link_to "Health", health_path%></li>
          <li class="<%= params[:action] == 'contact' ? 'tab_selected' : ''%>"><%= link_to "Contact Us", contact_path%></li>
        </ul>
      </div>
    </div>
    <%= yield %>
    <div id="footer">Copyright &copy; Bprds. All Rights Reserved. </div>
  </div>
</body>
</html>